name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [ '22' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B -DskipTests=false clean verify

      - name: Upload shaded JARs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: newbestsub-artifacts
          path: |
            target/*-jar-with-dependencies.jar
