name: Docs

on:
  push:
    branches: [ master, main ]
    tags:     [ 'v*' ]
  workflow_dispatch:

permissions:
  contents: write  # needed to push to gh-pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '22'
          cache: maven

      # This writes Dokka output to /docs thanks to the POM 'pages' profile
      - name: Build Dokka site (to /docs)
        run: mvn -B -ntp -Ppages -DskipTests=true clean verify site

      - name: Publish to GitHub Pages (gh-pages branch)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs
          # Optional first-time setup:
          # force_orphan: true
          # cname: docs.example.org
